spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  thymeleaf:
    cache: true

logging:
  level:
    root: INFO
    com.lois: INFO

lois:
  ip-whitelist:
    enabled: true
    allowed: ${ALLOWED_IPS}
    public-paths:
      - /
      - /reservations
      - /api/reservations
      - /css
      - /js
      - /images
      - /access-request

management:
  endpoints:
    web:
      exposure:
        include: health       # health 엔드포인트 웹으로 노출
  endpoint:
    health:
      show-details: never     # 상태만 UP/DOWN 보이게