spring:
  profiles:
    active: local
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.lois.management.domain
  configuration:
    map-underscore-to-camel-case: true