spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver



  thymeleaf:
    cache: true

logging:
  level:
    root: INFO
    com.lois: INFO

lois:
  ip-whitelist:
    enabled: true
    allowed: ${ALLOWED_IPS}
    public-paths:
      - /
      - /reservations
      - /api/reservations
      - /css
      - /js
      - /images
      - /access-request